### ISSUE TITLE
Can I use this in browser-like or limited environment?

### ISSUE THREAD

**Issue by linonetwo** [bluelovers/node-segment-dict#1]
Likes browser or electron-renderer process?

This looks likes a total rewrite in TS.

**Comment by bluelovers** [comment]
我想應該是可以的喔
不過你可能需要使用 webpack 來打包你的腳本

另外
即使我寫的讀取器loader 無法正確作用的話

單純將這個模組當作 dict 用 掛在 dependencies
然後用你原本魔改的腳本來讀取這些dict也行

雖然我想我應該沒寫什麼webpack無法打包的語法
除了那個假 SYNC 的 STREAM 以外

**Comment by bluelovers** [comment]
@linonetwo 另外透過 runkit 是可以跑 [novel-segment](https://npm.runkit.com/novel-segment)

**Comment by linonetwo** [comment]
我支援浏览器环境的方案是 把字典提前 inline 到 js 文件内：
https://github.com/linonetwo/segmentit/blob/8f705d325eeb9fe85f1fc5f6d885293951bc0935/src/knowledge/index.js#L2-L11

所以不需要通过 fs、path 等 node 模块来加载字典了，不需要特殊的配置就能在各种环境使用。

而且我导出 ESM 模块，所以可以把没用到的模块 treeshaking 去掉，也方便异步加载模块（然后 webpack 会自动把字典切分到独立的 chunk 里面）
https://github.com/linonetwo/segmentit/blob/8f705d325eeb9fe85f1fc5f6d885293951bc0935/package.json#L3-L5

**Comment by linonetwo** [comment]
[kuromojin](https://github.com/azu/kuromojin) 则是可以传一个 URL 过去

https://github.com/azu/kuromojin/blob/8e21bbce7e4c9daafa13fdec416dfdc2fa72a217/src/kuromojin.js#L8-L25

然后把这个 URL 传给 kuromoji.js 后，它会发起一个 XHR 请求来加载词典
https://github.com/takuyaa/kuromoji.js/blob/71ea8473bd119546977f22c61e4d52da28ac30a6/src/loader/BrowserDictionaryLoader.js#L39-L58

这就导致部署应用的时候需要做一些额外的修正 https://github.com/azu/nlp-pattern-match/issues/5

**Comment by linonetwo** [comment]
但你的 loader 好像没有针对浏览器做适配，所以在浏览器环境就会遇到问题 [try on stackblitz ReactJS](https://stackblitz.com/edit/react-anmrmy)

如果你认同上面两个方案中的某一个，我可以提 PR 帮你重构一下。

**Comment by linonetwo** [comment]
但你的 loader 好像没有针对浏览器做适配，所以在浏览器环境就会遇到问题 [try on stackblitz ReactJS](https://stackblitz.com/edit/react-anmrmy)

如果你认同上面两个方案中的某一个，我可以提 PR 帮你重构一下。

**Comment by bluelovers** [comment]
思路嘛... 好像沒有
我很多東西都寫完就忘了為什麼這麼做XD

以前用 `stream` 的原因 好像只是為了 一行一行讀取 以及 防止 記憶體 GC 問題

基本上至少希望能保持 `sync` 跟 `async` 兩種方式

以及能簡單的增加支援的格式(如果對外 API 能長的一樣最好了)
https://github.com/bluelovers/node-segment-dict/blob/master/lib/loader/segment/index.ts

選擇字典時能使用 簡單的 `*`
https://github.com/bluelovers/node-segment/blob/master/lib/index.ts#L44

---

不透過 fs 的讀取方式可以參考一下(預先弄成 json 之類格式)
https://github.com/bluelovers/novel-segment-cli/blob/master/index.ts#L228

**Comment by linonetwo** [comment]
> 預先弄成 json 之類格式

我感觉，如果想支援传入 `'dict_synonym/*'` 这样的字符串来在运行时读取文件的话，就不能预先 inline 到 js 里，也不能预先放一个 json 里面。
因为 ESM tree shaking 要求静态 export 静态 import，所以只能 import 已经在记忆体里的东西，所以采用这个方法 又想要在运行时读取文件的话，就意味着所有字典得都得预先加载在记忆体里，这就太大了，不可取。


所以只好参考 [kuromojin](https://github.com/azu/kuromojin) 的方案，在运行时检测现在是在浏览器里还是在 node 里，如果在浏览器里，就把字典名拼接到一个给定的 URL 后，用 XHR 加载。
这要求使用者多传入一个 option，就是字典所在的 static file server 的 URL，一般就是网站 URL + `static/`。

我有空看看怎么结合，把 XHR 包装成 `stream` 应该也是可以的。

**Comment by bluelovers** [comment]
hmm 那額外導出一個字典檔名清單?

**Comment by linonetwo** [comment]
如果 XHR 能递归读取文件夹就好了，如果不行的话，那的确得提取用一个脚本把 dict 目录 tree 一下，得到一个 json 清单，从而在读取 `*` 的时候能看着这个清单递归读取。

**Comment by bluelovers** [comment]
https://github.com/bluelovers/node-segment/tree/master/test/temp

**Comment by bluelovers** [comment]
```ts
import Segment from 'novel-segment/lib';
import fs from 'fs-extra';
import Bluebird from 'bluebird';
import { join } from "path";
import consola from "consola";

const __root = join(__dirname, '..', '..');

function buildCache()
{
	const CACHED_SEGMENT = createSegment();

	CACHED_SEGMENT.doSegment('');

	return Bluebird
		.resolve(fs.outputJSON(join(__root, 'lib/segment', 'cache.json'), CACHED_SEGMENT.DICT))
		.tap(() => {
			consola.success('done')
		})
}

function createSegment()
{
	return new Segment({
		autoCjk: true,
		optionsDoSegment: {
			convertSynonym: true,
		},
		all_mod: true,
	});
}

buildCache();
```

---

```ts
import Segment from 'novel-segment/lib/segment/core';
import { useModules } from 'novel-segment/lib/segment/methods/useModules2';
import getDefaultModList from 'novel-segment/lib/mod';

let CACHED_SEGMENT: Segment;

export function createSegment()
{
	return new Segment({
		autoCjk: true,
		optionsDoSegment: {
			convertSynonym: true,
		},
		all_mod: true,
	});
}

/**
 * @todo fix gc for webpack
 */
export async function getSegment()
{
	// @ts-ignore
	const DICT = await import( /* webpackChunkName: "segment" */ '~/lib/segment/cache.json');

	CACHED_SEGMENT = createSegment();

	useModules(CACHED_SEGMENT as any, getDefaultModList(CACHED_SEGMENT.options.all_mod));

	CACHED_SEGMENT.DICT = DICT;
	CACHED_SEGMENT.inited = true;

	return CACHED_SEGMENT
}

export default getSegment
```

**Comment by bluelovers** [comment]
https://segment-api.bluelovers.now.sh/?input=%E5%AF%B9%E4%BA%8E%E6%97%A7%E4%BA%BA%E7%B1%BB%E6%9D%A5%E8%AF%B4%EF%BC%8C%E9%AD%94%E7%B4%A0%E6%98%AF%E6%AF%92%E7%B4%A0%E3%80%82

**Comment by linonetwo** [comment]
你太牛了，大兄弟！

**Comment by linonetwo** [comment]
我最近在开发的 NLP 流程工具就要用到在线分词，我过一两周就试试看你的库，到时候把我那边的一些东西合并进来，我那个就不维护了。

**Comment by bluelovers** [comment]
https://github.com/bluelovers/ws-segment/blob/master/packages/%40novel-segment/api-server/index.ts

**Comment by linonetwo** [comment]
ws-segment 是这个项目的重构版本吗？

**Comment by bluelovers** [comment]
子項目
