### ISSUE TITLE
請問你的字典的授權是?

### ISSUE THREAD

**Issue by flier268** [bluelovers/node-segment-dict#3]
你好，我開發了一個程式，其中有用到簡繁轉換
但是由於簡體字省略一部分資訊，導致簡體轉繁體會出現問題，需要進行修正
感覺你在詞彙修正這塊做得很好，因此想使用你的字典
不知道你的字體的授權是什麼呢，跟node-segment一樣是MIT嗎?我想移植到我的程式上

如果可以的話，麻煩請告訴我字典裡面，aa|0xbb|cc，bb、cc是什麼意思，cc我猜測是優先度，bb呢?
感謝

**Comment by bluelovers** [comment]
bb 是 詞性
參考 https://github.com/bluelovers/node-segment/blob/master/lib/POSTAG.ts

-----------

授權什麼的我搞不懂呢XD

如果是 nodejs 的話 可以用 安裝為 依賴模組 的方式 來導入字典

移植到其他語言的話
要是有追加修正的部分 如果能回饋到這裡就好了

----

另外 詞彙修正的部分 是依賴於 [novel-segment](https://github.com/bluelovers/node-segment/blob/master/lib/Segment.ts#L688) 分詞後 才來修正的
以及 可以啟用搭配 [ZhtSynonymOptimizer.ts](https://github.com/bluelovers/node-segment/blob/master/lib/submod/ZhtSynonymOptimizer.ts) 此模組來自動修正字典內沒有的部分

-------------

而如果是不分詞 而要對詞彙進行轉換的話 則推薦用

https://www.npmjs.com/package/regexp-cjk

可以自動無視簡繁來進行詞彙轉換
而不需要一直追加 同詞彙的各種 簡繁用字

**Comment by flier268** [comment]
問授權的問題只是擔心我如果用了你的東西，而你有一天吃壞肚子很不爽，來找我麻煩而已

這邊希望你可以同意我使用node-segment-dict讓我可以用在ConvertZZ的詞彙修正功能上，您是否同意呢？

只是簡繁轉換的話，系統本身就有提供函數可以做到了，跟cjk-convert的功能好像重複了
我需要的是可以將軟件轉成軟體的，看來只能用node-segment-dict了
如果我只是依照字典的字數長度降冪排列，再依優先度或字元降冪排列，依序取代原字串呢？這樣會不會有大問題？

**Comment by bluelovers** [comment]
恩 ok 的唷 不用擔心

---

將字典轉成 trie 樹之後 在取代應該會比較保險一點

---

`軟件` 轉成 `軟體`

看樣子 你說的是 opencc 的字典功能
那麼就會變得跟 opencc 一樣 可能在某些狀況下會有詞語 錯誤轉換的問題發生

https://github.com/bluelovers/node-segment-dict/tree/master/dict/opencc/dictionary

這部分 是 複製來自 https://github.com/BYVoid/OpenCC
我只是將她獨立取出而已(並且沒有實際使用)

你可能需要去問 opencc

----------

目前 node-segment-dict 內 **有使用** 的字典是針對 錯字 以及 **可能會/已經** 發生誤轉換的字 來做處理
並且是基於分詞後才來處理
雖然一樣可以做到 用語轉換的功能

但如果不分詞的話 就變成 普通的 文字取代 而已

那樣的話 轉換字典 內的詞組 是不會符合你的需求
https://github.com/bluelovers/node-segment-dict/blob/master/dict/synonym/synonym.txt

**Comment by flier268** [comment]
我沒有用 trie 樹，我是從長的字串找到小的字串，都找不到再跳下一個字，如果找到了，位於a，長度為b，那麼下次就從a+b開始找，這樣就不會重複了
效能方面，如果是replace會很慢，因為他會一直建立新字串，所以我採用的是key-value，有排序功能的的字典檔，然後加到StringBuilder裡面(StringBuilder不會建立新字串)
https://github.com/flier268/ConvertZZ/blob/master/ConvertZZ/Moudle/FastReplace.cs

但感覺我好像搞錯了什麼，node-segment-dict怎麼好像只是個分詞程式?雖然我知道用分詞可以更準確，但沒學過node.js，感覺架構好像不太一樣，要完全轉過去C#還是有點障礙

**Comment by bluelovers** [comment]
沒錯喔 這裡的確是個 分詞程式 並不是簡繁轉換

而我只是 利用分詞的基礎上 來修正 繁簡轉換 所會發生錯誤 或者 做不到的部分

畢竟有些曖昧的 里后 xxx 之類 不能單純轉換 而需要判斷語句 才能做處理

所以想做到繁簡轉換的話 必須使用 其他程式 來處理

變成 簡轉繁 +  novel-segment 或者  先 novel-segment + 簡轉繁 + (然後可以再多一次 novel-segment )

**Comment by flier268** [comment]
分詞的流程是這樣嗎?
依照優先度降冪排列，從大的找到小的，找到了就包起來標記詞性(可能取代成別的什麼符號)

**Comment by bluelovers** [comment]
分詞流程 先把 

所有可能出現的 分詞組合 標記出來 
然後接下來依照算法(詞性 優先度 前後詞性 整體語句) 計算之後 
算出得分最高的結果 來當作 分詞後的結果

**Comment by flier268** [comment]
難怪說沒有標點符號太多字會崩潰，你這時間複雜度也太高了吧

**Comment by bluelovers** [comment]
基本上 我已經改良了 崩潰 問題
(採用 當結果數量 大於 一定程度之後 就放棄 試圖 去計算剩下的可能出現組合 僅針對現有的組合來計算)

以及 當 出現 連字 時 會自動跳過
